spring:
  application:
    name: NUCHECK
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

  datasource:
    url: ${DATABASE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true